FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir streamlit pandas numpy scikit-learn matplotlib openpyxl
COPY src/          ./src/
COPY streamlit_app/./streamlit_app/
COPY config/       ./config/
COPY artifacts/    ./artifacts/
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]
